INSERT INTO city (city) VALUES ('서울특별시');
INSERT INTO city (city) VALUES ('부산광역시');
INSERT INTO city (city) VALUES ('대구광역시');
INSERT INTO city (city) VALUES ('인천광역시');
INSERT INTO city (city) VALUES ('광주광역시');
INSERT INTO city (city) VALUES ('대전광역시');
INSERT INTO city (city) VALUES ('울산광역시');
INSERT INTO city (city) VALUES ('세종특별자치시');
INSERT INTO city (city) VALUES ('제주특별자치도');

INSERT INTO city (city) VALUES ('경기도 수원시');
INSERT INTO city (city) VALUES ('경기도 고양시');
INSERT INTO city (city) VALUES ('경기도 용인시');
INSERT INTO city (city) VALUES ('경기도 성남시');
INSERT INTO city (city) VALUES ('경기도 부천시');
INSERT INTO city (city) VALUES ('경기도 화성시');
INSERT INTO city (city) VALUES ('경기도 안산시');
INSERT INTO city (city) VALUES ('경기도 남양주시');
INSERT INTO city (city) VALUES ('경기도 안양시');
INSERT INTO city (city) VALUES ('경기도 평택시');
INSERT INTO city (city) VALUES ('경기도 시흥시');
INSERT INTO city (city) VALUES ('경기도 파주시');
INSERT INTO city (city) VALUES ('경기도 의정부시');
INSERT INTO city (city) VALUES ('경기도 김포시');
INSERT INTO city (city) VALUES ('경기도 광주시');
INSERT INTO city (city) VALUES ('경기도 광명시');
INSERT INTO city (city) VALUES ('경기도 군포시');
INSERT INTO city (city) VALUES ('경기도 하남시');
INSERT INTO city (city) VALUES ('경기도 오산시');
INSERT INTO city (city) VALUES ('경기도 양주시');
INSERT INTO city (city) VALUES ('경기도 이천시');
INSERT INTO city (city) VALUES ('경기도 구리시');
INSERT INTO city (city) VALUES ('경기도 안성시');
INSERT INTO city (city) VALUES ('경기도 포천시');
INSERT INTO city (city) VALUES ('경기도 의왕시');
INSERT INTO city (city) VALUES ('경기도 양평군');
INSERT INTO city (city) VALUES ('경기도 여주시');
INSERT INTO city (city) VALUES ('경기도 동두천시');
INSERT INTO city (city) VALUES ('경기도 가평군');
INSERT INTO city (city) VALUES ('경기도 과천시');
INSERT INTO city (city) VALUES ('경기도 연천군');

INSERT INTO city (city) VALUES ('강원도 춘천시');
INSERT INTO city (city) VALUES ('강원도 원주시');
INSERT INTO city (city) VALUES ('강원도 강릉시');
INSERT INTO city (city) VALUES ('강원도 동해시');
INSERT INTO city (city) VALUES ('강원도 태백시');
INSERT INTO city (city) VALUES ('강원도 속초시');
INSERT INTO city (city) VALUES ('강원도 삼척시');
INSERT INTO city (city) VALUES ('강원도 홍천군');
INSERT INTO city (city) VALUES ('강원도 횡성군');
INSERT INTO city (city) VALUES ('강원도 영월군');
INSERT INTO city (city) VALUES ('강원도 평창군');
INSERT INTO city (city) VALUES ('강원도 정선군');
INSERT INTO city (city) VALUES ('강원도 철원군');
INSERT INTO city (city) VALUES ('강원도 화천군');
INSERT INTO city (city) VALUES ('강원도 양구군');
INSERT INTO city (city) VALUES ('강원도 인제군');
INSERT INTO city (city) VALUES ('강원도 고성군');
INSERT INTO city (city) VALUES ('강원도 양양군');

INSERT INTO city (city) VALUES ('충청북도 청주시');
INSERT INTO city (city) VALUES ('충청북도 충주시');
INSERT INTO city (city) VALUES ('충청북도 제천시');
INSERT INTO city (city) VALUES ('충청북도 보은군');
INSERT INTO city (city) VALUES ('충청북도 옥천군');
INSERT INTO city (city) VALUES ('충청북도 영동군');
INSERT INTO city (city) VALUES ('충청북도 증평군');
INSERT INTO city (city) VALUES ('충청북도 진천군');
INSERT INTO city (city) VALUES ('충청북도 괴산군');
INSERT INTO city (city) VALUES ('충청북도 음성군');
INSERT INTO city (city) VALUES ('충청북도 단양군');

INSERT INTO city (city) VALUES ('충청남도 천안시');
INSERT INTO city (city) VALUES ('충청남도 공주시');
INSERT INTO city (city) VALUES ('충청남도 보령시');
INSERT INTO city (city) VALUES ('충청남도 아산시');
INSERT INTO city (city) VALUES ('충청남도 서산시');
INSERT INTO city (city) VALUES ('충청남도 논산시');
INSERT INTO city (city) VALUES ('충청남도 계룡시');
INSERT INTO city (city) VALUES ('충청남도 당진시');
INSERT INTO city (city) VALUES ('충청남도 금산군');
INSERT INTO city (city) VALUES ('충청남도 부여군');
INSERT INTO city (city) VALUES ('충청남도 서천군');
INSERT INTO city (city) VALUES ('충청남도 청양군');
INSERT INTO city (city) VALUES ('충청남도 홍성군');
INSERT INTO city (city) VALUES ('충청남도 예산군');
INSERT INTO city (city) VALUES ('충청남도 태안군');

INSERT INTO city (city) VALUES ('전라북도 전주시');
INSERT INTO city (city) VALUES ('전라북도 군산시');
INSERT INTO city (city) VALUES ('전라북도 익산시');
INSERT INTO city (city) VALUES ('전라북도 정읍시');
INSERT INTO city (city) VALUES ('전라북도 남원시');
INSERT INTO city (city) VALUES ('전라북도 김제시');
INSERT INTO city (city) VALUES ('전라북도 완주군');
INSERT INTO city (city) VALUES ('전라북도 진안군');
INSERT INTO city (city) VALUES ('전라북도 무주군');
INSERT INTO city (city) VALUES ('전라북도 장수군');
INSERT INTO city (city) VALUES ('전라북도 임실군');
INSERT INTO city (city) VALUES ('전라북도 순창군');
INSERT INTO city (city) VALUES ('전라북도 고창군');
INSERT INTO city (city) VALUES ('전라북도 부안군');

INSERT INTO city (city) VALUES ('전라남도 목포시');
INSERT INTO city (city) VALUES ('전라남도 여수시');
INSERT INTO city (city) VALUES ('전라남도 순천시');
INSERT INTO city (city) VALUES ('전라남도 나주시');
INSERT INTO city (city) VALUES ('전라남도 광양시');
INSERT INTO city (city) VALUES ('전라남도 담양군');
INSERT INTO city (city) VALUES ('전라남도 곡성군');
INSERT INTO city (city) VALUES ('전라남도 구례군');
INSERT INTO city (city) VALUES ('전라남도 고흥군');
INSERT INTO city (city) VALUES ('전라남도 보성군');
INSERT INTO city (city) VALUES ('전라남도 화순군');
INSERT INTO city (city) VALUES ('전라남도 장흥군');
INSERT INTO city (city) VALUES ('전라남도 강진군');
INSERT INTO city (city) VALUES ('전라남도 해남군');
INSERT INTO city (city) VALUES ('전라남도 영암군');
INSERT INTO city (city) VALUES ('전라남도 무안군');
INSERT INTO city (city) VALUES ('전라남도 함평군');
INSERT INTO city (city) VALUES ('전라남도 영광군');
INSERT INTO city (city) VALUES ('전라남도 장성군');
INSERT INTO city (city) VALUES ('전라남도 완도군');
INSERT INTO city (city) VALUES ('전라남도 진도군');
INSERT INTO city (city) VALUES ('전라남도 신안군');

INSERT INTO city (city) VALUES ('경상북도 포항시');
INSERT INTO city (city) VALUES ('경상북도 경주시');
INSERT INTO city (city) VALUES ('경상북도 김천시');
INSERT INTO city (city) VALUES ('경상북도 안동시');
INSERT INTO city (city) VALUES ('경상북도 구미시');
INSERT INTO city (city) VALUES ('경상북도 영주시');
INSERT INTO city (city) VALUES ('경상북도 영천시');
INSERT INTO city (city) VALUES ('경상북도 상주시');
INSERT INTO city (city) VALUES ('경상북도 문경시');
INSERT INTO city (city) VALUES ('경상북도 경산시');
INSERT INTO city (city) VALUES ('경상북도 군위군');
INSERT INTO city (city) VALUES ('경상북도 의성군');
INSERT INTO city (city) VALUES ('경상북도 청송군');
INSERT INTO city (city) VALUES ('경상북도 영양군');
INSERT INTO city (city) VALUES ('경상북도 영덕군');
INSERT INTO city (city) VALUES ('경상북도 청도군');
INSERT INTO city (city) VALUES ('경상북도 고령군');
INSERT INTO city (city) VALUES ('경상북도 성주군');
INSERT INTO city (city) VALUES ('경상북도 칠곡군');
INSERT INTO city (city) VALUES ('경상북도 예천군');
INSERT INTO city (city) VALUES ('경상북도 봉화군');
INSERT INTO city (city) VALUES ('경상북도 울진군');
INSERT INTO city (city) VALUES ('경상북도 울릉군');

INSERT INTO city (city) VALUES ('경상남도 창원시');
INSERT INTO city (city) VALUES ('경상남도 진주시');
INSERT INTO city (city) VALUES ('경상남도 통영시');
INSERT INTO city (city) VALUES ('경상남도 사천시');
INSERT INTO city (city) VALUES ('경상남도 김해시');
INSERT INTO city (city) VALUES ('경상남도 밀양시');
INSERT INTO city (city) VALUES ('경상남도 거제시');
INSERT INTO city (city) VALUES ('경상남도 양산시');
INSERT INTO city (city) VALUES ('경상남도 의령군');
INSERT INTO city (city) VALUES ('경상남도 함안군');
INSERT INTO city (city) VALUES ('경상남도 창녕군');
INSERT INTO city (city) VALUES ('경상남도 고성군');
INSERT INTO city (city) VALUES ('경상남도 남해군');
INSERT INTO city (city) VALUES ('경상남도 하동군');
INSERT INTO city (city) VALUES ('경상남도 산청군');
INSERT INTO city (city) VALUES ('경상남도 함양군');
INSERT INTO city (city) VALUES ('경상남도 거창군');
INSERT INTO city (city) VALUES ('경상남도 합천군');

INSERT INTO travel (id, courseName, city, night, days) VALUES (1, '드라마 명장면 포항편', '경상북도 포항시', 1, 2);
INSERT INTO travel (id, courseName, city, night, days) VALUES (2, '강릉 맛여행', '강원도 강릉시', 1, 2);
INSERT INTO travel (id, courseName, city, night, days) VALUES (3, '부산 이곳저곳', '부산광역시', 4, 5);
INSERT INTO travel (id, courseName, city, night, days) VALUES (4, '인천 우정 여행', '인천광역시', 2, 3);
INSERT INTO travel (id, courseName, city, night, days) VALUES (5, '식도락 여행', '부산광역시', 1, 2);

INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 1, '관광지', '호미곶');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 1, '카페', '어스피스커피');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 1, '식당', '바다랑대게');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 1, '관광지', '구룡포 일본인 가옥거리');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 1, '카페', '까멜리아');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 2, '관광지', '영일대해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 2, '카페', '컵넛');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 2, '관광지', '스페이스워크');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (1, '드라마 명장면 포항편', 2, '식당', '덮죽');

INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 1, '관광지', '하슬라아트월드');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 1, '식당', '조개상회');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 1, '관광지', '안목해변');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 1, '카페', '로지커피');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 2, '식당', '강릉한정식');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 2, '관광지', '강문해변');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (2, '강릉 맛여행', 2, '식당', '신짬');

INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 1, '관광지', '요트투어');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 1, '관광지', '더베이101');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 1, '식당', '대도식당');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 2, '관광지', '해운대해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 2, '관광지', '해리단길');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 2, '카페', '듀플릿');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 2, '식당', '해성막창');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 3, '식당', '수변최고돼지국밥');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 3, '관광지', '광안리해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 3, '식당', '숙달돼지');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 4, '관광지', '흰여울문화마을');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 4, '관광지', '부평깡통시장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (3, '부산 이곳저곳', 5, '관광지', '태종대');

INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 1, '관광지', '송도 센트럴파크');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 1, '식당', '신복관');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 1, '카페', '케이슨24');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 2, '관광지', '차이나타운');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 2, '식당', '연경');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 2, '관광지', '월미도');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 3, '식당', '선녀풍');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 3, '관광지', '을왕리해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (4, '인천 우정 여행', 3, '카페', '아리니');

INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 1, '관광지', '해운대해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 1, '카페', '랑데자뷰');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 1, '식당', '선창횟집');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 1, '관광지', '부산엑스더스카이');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 2, '관광지', '부평깡통시장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 2, '관광지', '광안리해수욕장');
INSERT INTO detailCourse (id, courseName, dayy, type, spotName) VALUES (5, '식도락 여행', 2, '식당', '평화김해뒷고기');

